### PR TITLE
feat: run on windows with wsl2

### PR DESCRIPTION
**Pull request by mikejgray**
https://matrix.to/#/!fSmTzeelJHuQezhZDa:matrix.org/$1yXy21Arg87ImzIxfG5C5yWKIkKaJVxFZSdb_oP3ngo?via=matrix.org&via=cyberia.club&via=mozilla.org

### CODE REVIEW

**Comment by ChanceNCounter** [comment]
With PulseAudio running on Windows, it's possible to run the Assistant natively under WSL. However, once I started Doing Stuff, I started producing BSODs that I never really figured out.

I came to associate them with launching Windows applications from a skill, but I never nailed it down.

Just a word of warning, and a reason to use this a *lot* before declaring it supported.

**Comment by mikejgray** [comment]
Fair callout, @ChanceNCounter . I do want to mention that Pulse is not running in Windows here, however - WSLG runs pulseaudio in a separate VM, which then passes through to the WSL2 distro. That intermediate VM handles the passing of audio back to Windows without ever running or installing PulseAudio.exe (that I'm aware of, anyway). So in theory the issues you described shouldn't happen here - but we should watch for them!

**Comment by goldyfruit** [comment]
@mikejgray awesome! :+1: 

Could you please rename the `docker-compose.wsl2.yml` to `docker-compose.windows.yml`, it will be clearer for people not really comfortable with what WSL2 means.

As well, could you please add a little section in the main `README` about Windows *(as I did for Mac OS)*?

image

**Comment by mikejgray** [comment]
> @mikejgray awesome! 👍
> 
> Could you please rename the `docker-compose.wsl2.yml` to `docker-compose.windows.yml`, it will be clearer for people not really comfortable with what WSL2 means.
> 
> As well, could you please add a little section in the main `README` about Windows _(as I did for Mac OS)_?
> 
> image

Done

**Pull request merged**
